### PR TITLE
Update to 2023-10-30 version

### PR DESCRIPTION
**Pull request by xelser**

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Looks like one of the runners is stuck.

**Comment by xelser** [comment]
is anything here that needs to be done? or is just the bot refusing to accept it?

**Comment by bbhtt** [comment]
No, nothing from your side can be done. I don't have access to runners, I've informed the person who has.

**Comment by bbhtt** [comment]
Here is a build https://buildbot.flathub.org/#/builders/6/builds/81723 

It fails on

> cp: cannot stat 'src/gtk-3.0/gtk-sea.css': No such file or directory

Something to fix

**Comment by xelser** [comment]
bot, build

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
https://buildbot.flathub.org/#/builders/6/builds/81723

> cp: cannot stat 'src/gtk-3.0/gtk-sea.css': No such file or directory

Build it locally once https://docs.flatpak.org/en/latest/first-build.html

**Comment by xelser** [comment]
i'll get to it when i have time, im quite busy

**Comment by xelser** [comment]
All good? :grin:

**Pull request merged**
